name: Deploy ON Push

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-lastest
    steps:
      - neme: Testing
        run: |
            echo "Testing CI/CD pipelines"
            echo "Petch x Poom"